In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical   # to_categorical is a fuction to do --> one hot encoding
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
iris =load_iris()
X =iris.data
y =iris.target

In [3]:
X.shape

(150, 4)

In [4]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
y.shape

(150,)

In [7]:
y = to_categorical(y,num_classes=3)  # this this code for ---> one hot encoding 

In [8]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

## Note : if your y in the form of one hot encoding then the loss you will use "categorical_crossentropy" that is log loss

## Note : if your y in the form of label encoding in the form of intergers then you will use the "sparse_categorical_crossentropy"


In [9]:
X_train,X_test,y_train,y_test = train_test_split (X,y,test_size=0.2,random_state=42)

In [10]:
 # scaling is import for --> all data come on same scale because model not undersatnd any one features of is more releying to predit 

Scalar = StandardScaler() # Create scaler object

X_train = Scalar.fit_transform(X_train)# Learn mean and standard deviation from training data and scale it

X_test = Scalar.transform(X_test)# Scale test data using same mean and standard deviation


In [11]:
X_train.shape[1]

4

Regularizers 

In [27]:
from tensorflow import keras

reg1 = keras.regularizers.L1(l1=0.001)  # you can aslo define like this or direct write L1 or that required  in layer 
reg2 = keras.regularizers.L2(l2=0.001)

In [28]:


model=Sequential()
model.add(Dense(32,activation='relu',input_shape=(X_train.shape[1],),kernel_regularizer=reg1))
model.add(Dense(16,activation='relu',kernel_regularizer=reg2))
model.add(Dense(3,activation='softmax'))

In [29]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 32)             │           160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 3)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 739 (2.89 KB)

 Trainable params: 739 (2.89 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [31]:
model.fit(
    X_train,
    y_train,
    epochs=200,
    batch_size=32,
    validation_data=(X_test,y_test)
)

Epoch 1/200


4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 60ms/step - accuracy: 0.3500 - loss: 1.1054 - val_accuracy: 0.5333 - val_loss: 1.0488
Epoch 2/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.4500 - loss: 1.0598 - val_accuracy: 0.6000 - val_loss: 1.0048
Epoch 3/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.6333 - loss: 1.0202 - val_accuracy: 0.8000 - val_loss: 0.9648
Epoch 4/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8000 - loss: 0.9850 - val_accuracy: 0.8667 - val_loss: 0.9274
Epoch 5/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8083 - loss: 0.9503 - val_accuracy: 0.8667 - val_loss: 0.8933
Epoch 6/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.8000 - loss: 0.9195 - val_accuracy: 0.8667 - val_loss: 0.8617
Epoch 7/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - accuracy: 0.8000 - loss: 0.8897 - val_accuracy: 0.8667 - val_loss: 0.8312
Epoch 8/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7917 - loss: 0.8617 - val_accuracy: 0.8667 - val_loss: 0.8003
Epoc

In [32]:
test_loss,test_acc=model.evaluate(X_test,y_test)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.0820


In [20]:
test_loss

0.9850488305091858

In [21]:
test_acc

0.6666666865348816

## Functional API 

In [19]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Model
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from torch.nn.modules import activation

np.random.seed(0)
tf.random.set_seed(0)

# Load iris dataset
iris =load_iris()
X =iris.data
y =iris.target

# Standardies features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# One hot encode the labels
encoder = OneHotEncoder(sparse_output=False)
y_one_hot =encoder.fit_transform(y.reshape(-1,1))

# train test split
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y_one_hot,test_size=0.2,random_state=0)

#Define the model using the Functional API
input = Input(shape=(X_train.shape[1],))
x= Dense(64,activation='relu')(input)
x= Dense(32,activation='relu')(x)
outputs =Dense(y_train.shape[1], activation='softmax')(x)

#create model
model = Model(inputs=input,outputs=outputs)

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

model.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=16,
    validation_data=(X_test,y_test)
)



Epoch 1/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step - accuracy: 0.5583 - loss: 1.0397 - val_accuracy: 0.6667 - val_loss: 0.9703
Epoch 2/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8333 - loss: 0.8758 - val_accuracy: 0.6667 - val_loss: 0.8438
Epoch 3/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8583 - loss: 0.7394 - val_accuracy: 0.6667 - val_loss: 0.7387
Epoch 4/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8583 - loss: 0.6273 - val_accuracy: 0.6667 - val_loss: 0.6571
Epoch 5/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8583 - loss: 0.5404 - val_accuracy: 0.6667 - val_loss: 0.5994
Epoch 6/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8583 - loss: 0.4773 - val_accuracy: 0.6667 - val_loss: 0.5579
Epoch 7/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8500 - loss: 0.4316 - val_accuracy: 0.6667 - val_loss: 0.5253
Epoch 8/30
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8667 - loss: 0.3976 - val_accuracy: 0.6667 - val_loss: 0.4968
Epoch 

In [20]:
test_loss,test_acc=model.evaluate(X_test,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.9667 - loss: 0.1463


In [21]:
model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 4)              │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 64)             │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,499 (29.30 KB)

 Trainable params: 2,499 (9.76 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,000 (19.54 KB)

In [22]:
'''
inputs = Input(shape=(10,))
x = Dense(5, activation='relu')(inputs)
x = Dense(4, activation='relu')(x)

o1=Dense(1,activation='linear')(x)
o2=Dense(3,activation='softmax')(x)

model=Model(inputs=inputs,outputs=[o1,o2])


model.compile(
    loss={o1:'mse',o2:'categorical_crossentropy'},
    optimizer='adam',
    metrics={o1:'mae',o2:'accuracy'})

    '''

"\ninputs = Input(shape=(10,))\nx = Dense(5, activation='relu')(inputs)\nx = Dense(4, activation='relu')(x)\n\no1=Dense(1,activation='linear')(x)\no2=Dense(3,activation='softmax')(x)\n\nmodel=Model(inputs=inputs,outputs=[o1,o2])\n\n\nmodel.compile(\n    loss={o1:'mse',o2:'categorical_crossentropy'},\n    optimizer='adam',\n    metrics={o1:'mae',o2:'accuracy'})\n\n    "